### PR TITLE
Fixes #29

### LINKED ISSUE #29: PMI2/PMI tests failed on slurm/pmix
We need to modify pmi2 and pmi clients to use PMIx_Get_nb or PMIx_Get(PMIX_TIMEOUT)

### PR DESCRIPTION
**Pull request by igor-ivanov**
Fixes https://github.com/pmix/master/issues/29

@rhc54 @artpol84 could you look at the changes

### CODE REVIEW

File: src/client/pmi1.c [hunk 1]
```diff
@@ -59,20 +61,37 @@ static int pmi_init = 0;
...
+    proc.rank = PMIX_RANK_UNDEF;
+
+    /* set controlling parameters
+     * PMIX_OPTIONAL - expect that these keys should be available on startup
+     * PMIX_TIMEOUT - meet legacy PMI requirement
+     */
+    PMIX_INFO_CONSTRUCT(&info[0]);
+    PMIX_INFO_CONSTRUCT(&info[1]);
+    PMIX_INFO_LOAD(&info[0], PMIX_OPTIONAL, &val_optinal, PMIX_BOOL);
+    PMIX_INFO_LOAD(&info[1], PMIX_TIMEOUT, &val_timeout, PMIX_INT);
```
Comment (rhc54) [inline src/client/pmi1.c]: Is it true that PMI had a hard-coded 10 second timeout?? I don't recall seeing that in any of the definition documents. Where did 10 seconds come from?

**Comment by rhc54** [comment]
FWIW: I also had started by writing the equivalent of fetch_by_key, and then realized that the way the hash table code works, anything stored with rank UNDEF was going into the same list anyway. So creating a new function didn't accomplish anything in terms of different storage. All the data winds up on a single list which we scan to find the values.

Which is why I decided not to add the new function and just continue to use the current one.

File: src/client/pmi1.c (hunk 1 above)
Comment (igor-ivanov) [inline src/client/pmi1.c]: nothing special here. Just to set something. Probably it should be increased.

**Comment by igor-ivanov** [comment]
@rhc54 The primary target to implement pmix_hash_fetch_by_key() is getting information about rank. So I need to enumerate all data with specific key ("modex" in my case) for all possible ranks. I do not have any information about max possible rank.

File: src/client/pmi1.c (hunk 1 above)
Comment (rhc54) [inline src/client/pmi1.c]: I can see doing this for testing, but I really am not comfortable with hard-coding timeout limits in the PMIx library itself. The time required for an operation will depend on the size of the job, the transport being used, the RM's efficiency, etc. It isn't something we should hard-code.

Comment (igor-ivanov) [inline src/client/pmi1.c]: @rhc54 A absolutelly agree that nobody can predict a time get operation is processed. 
My motivation to use timeout in PMI/PMI2 client is:
- Now calling get operation requesting non existing key for specific rank brings stuck of application (example PMI2_Info_GetNodeAttr()).
- pmi2/pmi do not have a possibility to use PMIx_Get_nb.
- We do not know exactly what keys are mandatory for PMI/PMI2
- I prefer to return NOT_FOUND status instead of blocking situation for legacy PMI/PMI2 api.
As as result 
I am considering timeout usage as a way of replacing /PMIx_Get_nb/ - /user defined wait call/ inside PMI/PMI2 clients.

What timeout value do you suggest to set?

**Comment by artpol84** [comment]
+1

File: src/client/pmi1.c (hunk 1 above)
Comment (rhc54) [inline src/client/pmi1.c]: Let's consider a moment what the legacy code's behavior would be in a similar circumstance. When using PMI/PMI2, the data is always collected and returned during the "fence" operation. Thus, any subsequent "get" can be immediately resolved as found or not.

My plan for our backward compatibility library was to provide exactly the same behavior. A call to "fence" from PMI/PMI2 should be a "fence with data return". All subsequent "get" calls should pass an info key directing the server not to seek the data from another location. In other words, we check the client's data store - if not found, we check the local server's data store, and return an error if the data isn't immediately present.

This eliminates the need for an artificial timeout and provides the exact same behavior as PMI/PMI2. I hope that makes sense.

Comment (igor-ivanov) [inline src/client/pmi1.c]: Are you ok with setting timeout as -1 to force blocking mode for PMI/PMI2 clients?

Comment (rhc54) [inline src/client/pmi1.c]: By "blocking mode", I take it you mean the mode I described where we only check the client's and the local server's data store? I'd prefer we just use a dedicated key for that - we have a precedent in _PMIX_OPTIONAL_ that tells us to check only the client's data store. We just need one that allows the check to also go to the server. It isn't a timeout as a request for a different behavior, so adding a key makes the most sense.

Comment (artpol84) [inline src/client/pmi1.c]: @rhc54 I agree with Ralph here.

Comment (rhc54) [inline src/client/pmi1.c]: One other point, just to be sure there is understanding. The _optional_ flag tells the client to not  request the data from the server if the client doesn't already have it. So giving both the _optional_flag plus a timeout or request to check the server won't accomplish anything - once we see the _optional_ flag, we'll never ask the server. This is why I am suggesting a new key that indicates we should check both client and local server, but don't wait or try to find the data elsewhere if it isn't immediately present.

Comment (igor-ivanov) [inline src/client/pmi1.c]: I am feeling that we continue our discussion about TIMEOUT topic in this PR. I think that we could do it in https://github.com/pmix/master/pull/28 or https://github.com/pmix/master/issues/27 places.
I can remove any references to timeout value provided as part of info parameter inside pmi/pmi2 support (in any case we do not support this capability now in pmix library).
Are there other comments related this PR?

Comment (ompiteam) [inline src/client/pmi1.c]: That's fine with me - I have no other comments relative to this PR. Thx!

Comment (rhc54) [inline src/client/pmi1.c]: sorry about that - forgot to logout of the admin account after doing something. No other comments - thx!

**Comment by igor-ivanov** [comment]
Removed timeout usage because it means nothing on current code and there is no agreement about usage of one.
